In [1]:
import torch
torch.cuda.is_available()

True

In [21]:
a = torch.ones([2,3,4])
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [4]:
a.shape

torch.Size([2, 3, 4])

In [22]:
a= a.sum([0,2])
a

tensor([8., 8., 8.])

In [23]:
a.shape

torch.Size([3])

In [24]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [25]:
x.requires_grad_(True)
x.grad

In [26]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [28]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [29]:
x.grad==4*x

tensor([True, True, True, True])

In [30]:
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])